# Generated by Django 4.1 on 2022-09-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carnet', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=40)),
                ('addres', models.CharField(max_length=40)),
                ('gender', models.IntegerField(choices=[[0, 'Hombre'], [1, 'mujer']])),
                ('phone', models.CharField(max_length=8)),
                ('age', models.DateField()),
                ('career', models.CharField(max_length=50)),
                ('options', models.IntegerField(choices=[[0, 'lirica'], [1, 'epica'], [2, 'dramatica']])),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('fecha_declaracion', models.DateField()),
            ],
        ),
    ]
